var agentobj = [
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Amazon Relationship Books",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-01T11:22:02.000Z",
    "modified": "2018-04-01T11:22:02.000Z",
    "aid": 377,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 358,
    "examples": 2,
    "model": "{\"keywords\":{\"kindle relationship books-All-Keywords\":{\"keyword\":\"kindle relationship books\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"All\",\"type\":\"Keywords\",\"searched\":true},\"relationship books-All-Keywords\":{\"keyword\":\"relationship books\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"All\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Romantic gifts",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-07T13:11:47.000Z",
    "modified": "2018-04-07T13:11:47.000Z",
    "aid": 380,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 361,
    "examples": 3,
    "model": "{\"keywords\":{\"love gifts-All-Keywords\":{\"keyword\":\"love gifts\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"All\",\"type\":\"Keywords\",\"searched\":true},\"romantic gifts for her-All-Keywords\":{\"keyword\":\"romantic gifts for her\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"All\",\"type\":\"Keywords\",\"searched\":true},\"romantic gifts-All-Keywords\":{\"keyword\":\"romantic gifts\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"All\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Bot2Bot for Little Things Love Bot",
    "description": "For SeinfeldBot",
    "amazonid": null,
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 0,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-20T15:24:35.000Z",
    "modified": "2018-04-20T15:24:35.000Z",
    "aid": 386,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": 5,
    "bot2bot": 1,
    "boturl": "https://m.me/littlethingslovebot",
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": null,
    "examples": null,
    "model": null,
    "complete": null,
    "training": null,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "New York Times best seller",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-22T03:34:23.000Z",
    "modified": "2018-04-22T03:34:23.000Z",
    "aid": 388,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 364,
    "examples": 4,
    "model": "{\"keywords\":{\"fiction new releases-Books-Keywords\":{\"keyword\":\"fiction new releases\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"best sellers fiction 2018-Books-Keywords\":{\"keyword\":\"best sellers fiction 2018\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"best sellers fiction-Books-Keywords\":{\"keyword\":\"best sellers fiction\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"fiction-Books-Keywords\":{\"keyword\":\"fiction\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Romance books",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-22T14:57:20.000Z",
    "modified": "2018-04-22T14:57:20.000Z",
    "aid": 389,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 365,
    "examples": 3,
    "model": "{\"keywords\":{\"romance-Books-Keywords\":{\"keyword\":\"romance\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"romance new releases-Books-Keywords\":{\"keyword\":\"romance new releases\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"romance best sellers-Books-Keywords\":{\"keyword\":\"romance best sellers\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Suspense, thriller and mystery",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-22T15:45:50.000Z",
    "modified": "2018-04-22T15:45:50.000Z",
    "aid": 390,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 366,
    "examples": 10,
    "model": "{\"keywords\":{\"thriller new releases-Books-Keywords\":{\"keyword\":\"thriller new releases\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"suspense new releases-Books-Keywords\":{\"keyword\":\"suspense new releases\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"mystery new releases-Books-Keywords\":{\"keyword\":\"mystery new releases\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"mystery best seller-Books-Keywords\":{\"keyword\":\"mystery best seller\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"suspense best sellers 2018-Books-Keywords\":{\"keyword\":\"suspense best sellers 2018\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"thriller best sellers 2018-Books-Keywords\":{\"keyword\":\"thriller best sellers 2018\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"suspense best sellers-Books-Keywords\":{\"keyword\":\"suspense best sellers\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"thriller best sellers-Books-Keywords\":{\"keyword\":\"thriller best sellers\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"Mystery best sellers-Books-Keywords\":{\"keyword\":\"Mystery best sellers\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"Mystery best sellers 2018-Books-Keywords\":{\"keyword\":\"Mystery best sellers 2018\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Biographies & Memoirs",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-24T16:32:24.000Z",
    "modified": "2018-04-24T16:32:24.000Z",
    "aid": 391,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 367,
    "examples": 6,
    "model": "{\"keywords\":{\"biographies best sellers-Books-Keywords\":{\"keyword\":\"biographies best sellers\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"memoirs best sellers-Books-Keywords\":{\"keyword\":\"memoirs best sellers\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"memoirs new releases-All-Keywords\":{\"keyword\":\"memoirs new releases\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"All\",\"type\":\"Keywords\",\"searched\":true},\"biographies new releases-All-Keywords\":{\"keyword\":\"biographies new releases\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"All\",\"type\":\"Keywords\",\"searched\":true},\"biographies-Books-Keywords\":{\"keyword\":\"biographies\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"memoirs-Books-Keywords\":{\"keyword\":\"memoirs\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Science fiction & Fantasy",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-25T07:15:10.000Z",
    "modified": "2018-04-25T07:15:10.000Z",
    "aid": 392,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 368,
    "examples": 6,
    "model": "{\"keywords\":{\"science fiction new releases-Books-Keywords\":{\"keyword\":\"science fiction new releases\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"fantasy new releases-Books-Keywords\":{\"keyword\":\"fantasy new releases\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"fantasy best seller-Books-Keywords\":{\"keyword\":\"fantasy best seller\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"science fiction best seller-Books-Keywords\":{\"keyword\":\"science fiction best seller\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"fantasy-Books-Keywords\":{\"keyword\":\"fantasy\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true},\"science fiction-Books-Keywords\":{\"keyword\":\"science fiction\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Erotica",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-04-25T08:04:20.000Z",
    "modified": "2018-04-25T08:04:20.000Z",
    "aid": 393,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 369,
    "examples": 1,
    "model": "{\"keywords\":{\"erotica-KindleStore-Keywords\":{\"keyword\":\"erotica\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "My bucket list journal",
    "description": null,
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-05-15T12:03:31.000Z",
    "modified": "2018-05-15T12:03:31.000Z",
    "aid": 429,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 401,
    "examples": 1,
    "model": "{\"keywords\":{\"bucket list journal for couples-Books-Keywords\":{\"keyword\":\"bucket list journal for couples\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"Books\",\"type\":\"Keywords\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Personal Finance",
    "description": "Personal Finance books",
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 1,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-07-03T05:53:12.000Z",
    "modified": "2018-07-03T05:53:12.000Z",
    "aid": 503,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": null,
    "bot2bot": 0,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 475,
    "examples": 7,
    "model": "{\"keywords\":{\"rich dad poor dad-KindleStore-Keywords\":{\"keyword\":\"rich dad poor dad\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Keywords\",\"searched\":true},\"cashflow quadrant-KindleStore-Keywords\":{\"keyword\":\"cashflow quadrant\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Keywords\",\"searched\":true},\"rich dad for teens-KindleStore-Keywords\":{\"keyword\":\"rich dad for teens\",\"options\":{\"sort\":false,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Keywords\",\"searched\":true},\"guide to money-KindleStore-Keywords\":{\"keyword\":\"guide to money\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Keywords\",\"searched\":true},\"making money-KindleStore-Keywords\":{\"keyword\":\"making money\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Keywords\",\"searched\":true},\"becoming rich-KindleStore-Title\":{\"keyword\":\"becoming rich\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Title\",\"searched\":true},\"personal finance-KindleStore-Title\":{\"keyword\":\"personal finance\",\"options\":{\"sort\":true,\"related\":false,\"minprice\":0,\"maxprice\":0},\"error\":null,\"index\":\"KindleStore\",\"type\":\"Title\",\"searched\":true}}}",
    "complete": 1,
    "training": 0,
    "progress": 100
  },
  {
    "email": "accountingeducation@up.ac.za",
    "type": "API_KEY",
    "name": "Eros Cashbot AI Agent",
    "description": "The new Cashbot AI agent, for Eros",
    "amazonid": "stephencoetze-20",
    "chatfuel": 1,
    "nodejs": 0,
    "amazon": 0,
    "shopify": 0,
    "enabled": 1,
    "created": "2018-08-14T16:37:21.000Z",
    "modified": "2018-08-14T16:37:21.000Z",
    "aid": 580,
    "locale": "US",
    "uid": 370,
    "sid": null,
    "b2bid": 1,
    "bot2bot": 1,
    "boturl": null,
    "ai": 0,
    "shopifyname": null,
    "shopifytoken": null,
    "mid": 547,
    "examples": 0,
    "model": null,
    "complete": 0,
    "training": 0,
    "progress": 100
  }
]

